import * as Heading from './Heading';
export const H1 = Heading.H1;
export const H2 = Heading.H2;
export { default as Asciidoc } from './Asciidoc';
export { default as Html } from './Html';
export { default as Code } from './Code';
export { default as Para } from './Para';
export { default as Section } from './Section';
export { default as Pair } from './Pair';
export { default as Note } from './Note';
