name: meta
inputs:
  github_token:
    required: true
outputs:
  latest_commit_sha:
    description: Full sha of latest commit, for any type of event
  latest_commit_sha_short:
    description: Short sha of latest commit, for any type of event
  pull_request_number:
    description: Pull request number, if available
  pull_request_title:
    description: Pull request title, if available
runs:
  using: node12
  main: ./bundled/index.js
