name: lint-asciidoc

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  lint:
    name: run-lint-adoc
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: trilom/file-changes-action@v1.2.3
        with:
          token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: friends-library/friends-library
          path: fl
      - name: yarn
        run: cd fl/packages/adoc-lint && yarn
      - name: compile
        run: cd fl && yarn compile adoc-lint
      - name: lint
        uses: friends-library/friends-library/actions/lint-adoc@master
