name: lint-asciidoc

on: [pull_request]

jobs:
  lint:
    name: run-lint-adoc
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: trilom/file-changes-action@v1.2.4
        with:
          githubToken: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: lint
        uses: friends-library/friends-library/actions/lint-adoc@actions
        with:
          github_token: ${{ github.token }}
