name: pdf-previews

on: [pull_request]

jobs:
  pdfpreview:
    name: pdf-previews
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    env:
      PRINCE_BIN: /home/runner/bin/prince-books
      PRINCE_FILENAME: prince-books-20191125-ubuntu18.04-amd64
      CLOUD_STORAGE_BUCKET_URL: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
      CLOUD_STORAGE_BUCKET: ${{ secrets.CLOUD_STORAGE_BUCKET }}
      CLOUD_STORAGE_ENDPOINT: ${{ secrets.CLOUD_STORAGE_ENDPOINT }}
      CLOUD_STORAGE_KEY: ${{ secrets.CLOUD_STORAGE_KEY }}
      CLOUD_STORAGE_SECRET: ${{ secrets.CLOUD_STORAGE_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: download pdf binary
        run: |
          curl -s ${CLOUD_STORAGE_BUCKET_URL}/actions/${PRINCE_FILENAME}.tar.gz > ~/prince.tar.gz
          tar -xvzf ~/prince.tar.gz -C ~ > /dev/null
          printf "$HOME\n" | ~/${PRINCE_FILENAME}/install.sh
      - name: get changed files
        uses: trilom/file-changes-action@v1.2.4
        with:
          githubToken: ${{ github.token }}
      - name: create pdf previews
        uses: friends-library/friends-library/actions/pdf@actions
        with:
          GITHUB_TOKEN: ${{ github.token }}
