[.lead]
Although early Quakers wrote in what is technically considered "`early modern English,`"
their writings don't seem very modern to most readers today.
In fact, it has been our experience that very few are able or willing to overcome the obstacles
presented by the grammar and vocabulary of 17th and 18th century English.
Because we strongly believe that these writings deserve the widest audience possible,
and that early Friends would never have wanted the evolution of language
to become a stumbling block in the way of future generations,
we have worked hard to provide minimally and carefully modernized versions
of each of the documents offered on this website.

++++
<Divider />
++++

== About our Modernization

Our core philosophy in modernization is to change as little as possible in
order to make the text clear in today’s English.
Wherever possible, we try to retain the original language and phrasing.
The vast majority of changes involve simply updating pronouns (_thee_, _thou_, _ye_),
verb endings (know__est__, would__st__, do__th__),
and making careful substitutions for words that have changed meaning or are no longer used.
Sometimes, however, changes in word order and phrasing are also
very helpful in clarifying the original intent of the author.

Modernizing is not a simple or straightforward task, and can easily be done poorly.
Attempts to modernize Quaker documents without a deep understanding of their context, vocabulary,
religious culture, and peculiar testimonies have led to some
http://www.qhpress.org/texts/barclay/apology/appendix.html[very unsatisfactory results].
For this reason, we approach the task with the greatest care and seriousness,
and trust that we are in measure qualified for the work by a true intimacy with the body of literature,
having read and re-read many thousands of pages (in their original format)
for our own personal edification and enjoyment;
also by a heartfelt agreement with the spiritual views contained in them;
by a very real sense of loving esteem and respect for the original authors;
by an admittedly imperfect but sincere attempt to live
by the same light and grace to which the Quakers testified;
and by a measure of the fear of the Lord--believing that the
Spirit of God is the true source of much of what is presented in their writings.

It is extremely important to us to make clear that every bit of modernization
represented on this site was undertaken with the goal of clarifying for modern
ears what the original authors were trying to communicate.
No attempts whatsoever have been made to alter or update any sentiment or doctrine expressed.
Quite the opposite is actually the case.
It is only because of our great love and respect for the men and women who wrote these works,
and our firm belief in the biblical soundness and essential truth of the doctrines and testimonies
of the original Society of Friends,
that we have attempted the work of modernization in the first place.

We have tried to do all of our modernization with a high degree of transparency.
We always make the original, un-modernized versions of these writings available alongside the modernized ones,
and we heartily welcome and encourage anyone to read these original versions,
or to compare the two texts to see the nature of our changes.

== About the Editions

You will find three different _editions_ of books in various places throughout this website.
Editions labeled _Original_ are untouched except for an occasional modernization of spelling,
and the basic formatting of paragraphs, headings, footnotes, etc.
_Modernized_ editions have had pronouns, verb endings, and some archaic words updated,
but are otherwise essentially the same as the original versions and are unabridged.
Finally, some of our favorite works are available in what we call an _Updated_ edition.
We use the term Updated to indicate that these editions contain further editing beyond the modernized version.
Examples of the types of edits made to updated editions include:

* Extracting a stand-alone book from a longer work.

* Combining two smaller works that address the same subject/s and complement each 	other.

* Omitting some material because of obscure historical references, repetition, political contexts, lengthy travel logs, etc.

* Producing a shorter work that contains selections from an original document.

* Careful rewording of difficult or confusing sentences.

== Examples of Modernization

To give you a better idea of exactly what we do to modernize these documents,
below are a few examples of the major types of changes we make.

As mentioned previously,
a large portion of our modernization is simply a matter of updating spelling and word endings.
The following is a short list of antiquated spellings that have been changed in our modernized versions:
_dost_ has been changed to _do_, _hast_ to _have_, _burthen_ to _burden_, _whilst_ to _while_,
_durst_ to _dared_, _wert_ to _were_, _betwixt_ to _between_, _shew_ to _show_, _hither_ to _here_,
_thither_ to _there_, _mayest_ to _may_, etc.

Other words may look identical to English words used today,
but their meaning or usage has actually changed over time.
These can be particularly confusing to modern readers. Some examples are below:

suffer::
often meant _allow_ or _permit_, i.e. "`I will not suffer him to enter.`"

want::
was almost always used to mean _lack_ or _need_, i.e. "`He died for want of food.`"

conversation::
often meant _conduct_ or _manner of life_, i.e. "`He was a man of clean conversation`"

meet::
was used to signify _fit_ or _fitting_, i.e., "`I will go wherever the Lord sees meet to lead me.`"

moment::
sometimes meant _importance_, i.e. "`This issue is of great moment.`"

Still other words are simply no longer used in contemporary English.
In our modernized versions, each of these words is looked at in its context,
and a present-day equivalent is carefully chosen.
The following are a just few examples:

physic::
means medicine

wonted::
means customary, normal, or characteristic

vouchsafe::
means to grant or graciously give

an assizes::
is a court session

victuals::
means food

Popery::
means Roman Catholicism

loth or loath::
means reluctant or unwilling

gaol::
is the old word for jail

The following sentence from Isaac Penington’s works is a good example
of the type of transformation that a sentence may undergo.
The original text reads:

""
Thou takest up Cain’s weapons, and fain wouldst thou kill thy brother,
because his sacrifice in the faith testifies against thine.
""

Our modernized sentence reads:

""
You take up Cain’s weapons, and you would eagerly kill your brother,
because his sacrifice in the faith testifies against yours.
""

As you can see in this example,
the meaning of the Penington's original sentence has not been lost or obscured.
But by updating some pronouns and verb endings,
substituting the archaic word fain for its modern equivalent eagerly,
and slightly changing the order of words,
we have constructed a sentence that is significantly more approachable for readers of today.
