// flow-typed signature: c3fd0b347b12e825985fcf2a8e4d1cda
// flow-typed version: <<STUB>>/@emotion/core_v10.0.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/core/dist/core.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/core/dist/core.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/core/dist/core.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/core/dist/core.cjs' {
  declare module.exports: any;
}

declare module '@emotion/core/dist/core.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/core/dist/core.esm' {
  declare module.exports: any;
}

declare module '@emotion/core/dist/core.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/core/src/class-names' {
  declare module.exports: any;
}

declare module '@emotion/core/src/context' {
  declare module.exports: any;
}

declare module '@emotion/core/src/global' {
  declare module.exports: any;
}

declare module '@emotion/core/src/index' {
  declare module.exports: any;
}

declare module '@emotion/core/src/jsx' {
  declare module.exports: any;
}

declare module '@emotion/core/src/keyframes' {
  declare module.exports: any;
}

declare module '@emotion/core/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/core/dist/core.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/core/dist/core.browser.cjs'>;
}
declare module '@emotion/core/dist/core.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/core/dist/core.browser.esm'>;
}
declare module '@emotion/core/dist/core.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/core/dist/core.cjs.dev'>;
}
declare module '@emotion/core/dist/core.cjs.js' {
  declare module.exports: $Exports<'@emotion/core/dist/core.cjs'>;
}
declare module '@emotion/core/dist/core.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/core/dist/core.cjs.prod'>;
}
declare module '@emotion/core/dist/core.esm.js' {
  declare module.exports: $Exports<'@emotion/core/dist/core.esm'>;
}
declare module '@emotion/core/dist/core.umd.min.js' {
  declare module.exports: $Exports<'@emotion/core/dist/core.umd.min'>;
}
declare module '@emotion/core/src/class-names.js' {
  declare module.exports: $Exports<'@emotion/core/src/class-names'>;
}
declare module '@emotion/core/src/context.js' {
  declare module.exports: $Exports<'@emotion/core/src/context'>;
}
declare module '@emotion/core/src/global.js' {
  declare module.exports: $Exports<'@emotion/core/src/global'>;
}
declare module '@emotion/core/src/index.js' {
  declare module.exports: $Exports<'@emotion/core/src/index'>;
}
declare module '@emotion/core/src/jsx.js' {
  declare module.exports: $Exports<'@emotion/core/src/jsx'>;
}
declare module '@emotion/core/src/keyframes.js' {
  declare module.exports: $Exports<'@emotion/core/src/keyframes'>;
}
declare module '@emotion/core/src/utils.js' {
  declare module.exports: $Exports<'@emotion/core/src/utils'>;
}
