// flow-typed signature: 7e961ef67a079c46d04ce2584b3af570
// flow-typed version: <<STUB>>/@emotion/styled_v10.0.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/styled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/styled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/styled/dist/styled.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/styled.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/styled.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/styled.cjs' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/styled.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/styled.esm' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/styled.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/styled/macro' {
  declare module.exports: any;
}

declare module '@emotion/styled/src/index' {
  declare module.exports: any;
}

declare module '@emotion/styled/src/tags' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/styled/dist/styled.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/styled.browser.cjs'>;
}
declare module '@emotion/styled/dist/styled.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/styled.browser.esm'>;
}
declare module '@emotion/styled/dist/styled.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/styled.cjs.dev'>;
}
declare module '@emotion/styled/dist/styled.cjs.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/styled.cjs'>;
}
declare module '@emotion/styled/dist/styled.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/styled.cjs.prod'>;
}
declare module '@emotion/styled/dist/styled.esm.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/styled.esm'>;
}
declare module '@emotion/styled/dist/styled.umd.min.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/styled.umd.min'>;
}
declare module '@emotion/styled/macro.js' {
  declare module.exports: $Exports<'@emotion/styled/macro'>;
}
declare module '@emotion/styled/src/index.js' {
  declare module.exports: $Exports<'@emotion/styled/src/index'>;
}
declare module '@emotion/styled/src/tags.js' {
  declare module.exports: $Exports<'@emotion/styled/src/tags'>;
}
