// flow-typed signature: 20dfb84bf64955ef47aa8a3ead5986da
// flow-typed version: <<STUB>>/@slack/client_v^4.8.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@slack/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@slack/client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@slack/client/dist/errors' {
  declare module.exports: any;
}

declare module '@slack/client/dist/IncomingWebhook' {
  declare module.exports: any;
}

declare module '@slack/client/dist/index' {
  declare module.exports: any;
}

declare module '@slack/client/dist/KeepAlive' {
  declare module.exports: any;
}

declare module '@slack/client/dist/logger' {
  declare module.exports: any;
}

declare module '@slack/client/dist/methods' {
  declare module.exports: any;
}

declare module '@slack/client/dist/retry-policies' {
  declare module.exports: any;
}

declare module '@slack/client/dist/RTMClient' {
  declare module.exports: any;
}

declare module '@slack/client/dist/util' {
  declare module.exports: any;
}

declare module '@slack/client/dist/WebClient' {
  declare module.exports: any;
}

// Filename aliases
declare module '@slack/client/dist/errors.js' {
  declare module.exports: $Exports<'@slack/client/dist/errors'>;
}
declare module '@slack/client/dist/IncomingWebhook.js' {
  declare module.exports: $Exports<'@slack/client/dist/IncomingWebhook'>;
}
declare module '@slack/client/dist/index.js' {
  declare module.exports: $Exports<'@slack/client/dist/index'>;
}
declare module '@slack/client/dist/KeepAlive.js' {
  declare module.exports: $Exports<'@slack/client/dist/KeepAlive'>;
}
declare module '@slack/client/dist/logger.js' {
  declare module.exports: $Exports<'@slack/client/dist/logger'>;
}
declare module '@slack/client/dist/methods.js' {
  declare module.exports: $Exports<'@slack/client/dist/methods'>;
}
declare module '@slack/client/dist/retry-policies.js' {
  declare module.exports: $Exports<'@slack/client/dist/retry-policies'>;
}
declare module '@slack/client/dist/RTMClient.js' {
  declare module.exports: $Exports<'@slack/client/dist/RTMClient'>;
}
declare module '@slack/client/dist/util.js' {
  declare module.exports: $Exports<'@slack/client/dist/util'>;
}
declare module '@slack/client/dist/WebClient.js' {
  declare module.exports: $Exports<'@slack/client/dist/WebClient'>;
}
