// flow-typed signature: e4a79ff1f701a1ba44a0a6012fca2954
// flow-typed version: <<STUB>>/codemirror-asciidoc_v^1.0.4/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror-asciidoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror-asciidoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codemirror-asciidoc/lib/asciidoc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codemirror-asciidoc/lib/asciidoc.js' {
  declare module.exports: $Exports<'codemirror-asciidoc/lib/asciidoc'>;
}
