// flow-typed signature: b143588a736ac7648ba1454da286b0b7
// flow-typed version: <<STUB>>/electron-better-ipc_v^0.1.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-better-ipc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-better-ipc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-better-ipc/source/main' {
  declare module.exports: any;
}

declare module 'electron-better-ipc/source/renderer' {
  declare module.exports: any;
}

declare module 'electron-better-ipc/source/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-better-ipc/index' {
  declare module.exports: $Exports<'electron-better-ipc'>;
}
declare module 'electron-better-ipc/index.js' {
  declare module.exports: $Exports<'electron-better-ipc'>;
}
declare module 'electron-better-ipc/source/main.js' {
  declare module.exports: $Exports<'electron-better-ipc/source/main'>;
}
declare module 'electron-better-ipc/source/renderer.js' {
  declare module.exports: $Exports<'electron-better-ipc/source/renderer'>;
}
declare module 'electron-better-ipc/source/util.js' {
  declare module.exports: $Exports<'electron-better-ipc/source/util'>;
}
