// flow-typed signature: 97db68073f20a97b21a83c95e62911c2
// flow-typed version: <<STUB>>/emotion-theming_v10.0.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-theming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-theming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-theming/dist/emotion-theming.browser.cjs' {
  declare module.exports: any;
}

declare module 'emotion-theming/dist/emotion-theming.browser.esm' {
  declare module.exports: any;
}

declare module 'emotion-theming/dist/emotion-theming.cjs.dev' {
  declare module.exports: any;
}

declare module 'emotion-theming/dist/emotion-theming.cjs' {
  declare module.exports: any;
}

declare module 'emotion-theming/dist/emotion-theming.cjs.prod' {
  declare module.exports: any;
}

declare module 'emotion-theming/dist/emotion-theming.esm' {
  declare module.exports: any;
}

declare module 'emotion-theming/dist/emotion-theming.umd.min' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/index' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/theme-provider' {
  declare module.exports: any;
}

declare module 'emotion-theming/src/with-theme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-theming/dist/emotion-theming.browser.cjs.js' {
  declare module.exports: $Exports<'emotion-theming/dist/emotion-theming.browser.cjs'>;
}
declare module 'emotion-theming/dist/emotion-theming.browser.esm.js' {
  declare module.exports: $Exports<'emotion-theming/dist/emotion-theming.browser.esm'>;
}
declare module 'emotion-theming/dist/emotion-theming.cjs.dev.js' {
  declare module.exports: $Exports<'emotion-theming/dist/emotion-theming.cjs.dev'>;
}
declare module 'emotion-theming/dist/emotion-theming.cjs.js' {
  declare module.exports: $Exports<'emotion-theming/dist/emotion-theming.cjs'>;
}
declare module 'emotion-theming/dist/emotion-theming.cjs.prod.js' {
  declare module.exports: $Exports<'emotion-theming/dist/emotion-theming.cjs.prod'>;
}
declare module 'emotion-theming/dist/emotion-theming.esm.js' {
  declare module.exports: $Exports<'emotion-theming/dist/emotion-theming.esm'>;
}
declare module 'emotion-theming/dist/emotion-theming.umd.min.js' {
  declare module.exports: $Exports<'emotion-theming/dist/emotion-theming.umd.min'>;
}
declare module 'emotion-theming/src/index.js' {
  declare module.exports: $Exports<'emotion-theming/src/index'>;
}
declare module 'emotion-theming/src/theme-provider.js' {
  declare module.exports: $Exports<'emotion-theming/src/theme-provider'>;
}
declare module 'emotion-theming/src/with-theme.js' {
  declare module.exports: $Exports<'emotion-theming/src/with-theme'>;
}
