// flow-typed signature: 5a053debd5eab74d6954fd5be3ecbcf8
// flow-typed version: <<STUB>>/gettext-parser_v^1.3.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gettext-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gettext-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gettext-parser/lib/mocompiler' {
  declare module.exports: any;
}

declare module 'gettext-parser/lib/moparser' {
  declare module.exports: any;
}

declare module 'gettext-parser/lib/pocompiler' {
  declare module.exports: any;
}

declare module 'gettext-parser/lib/poparser' {
  declare module.exports: any;
}

declare module 'gettext-parser/lib/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gettext-parser/index' {
  declare module.exports: $Exports<'gettext-parser'>;
}
declare module 'gettext-parser/index.js' {
  declare module.exports: $Exports<'gettext-parser'>;
}
declare module 'gettext-parser/lib/mocompiler.js' {
  declare module.exports: $Exports<'gettext-parser/lib/mocompiler'>;
}
declare module 'gettext-parser/lib/moparser.js' {
  declare module.exports: $Exports<'gettext-parser/lib/moparser'>;
}
declare module 'gettext-parser/lib/pocompiler.js' {
  declare module.exports: $Exports<'gettext-parser/lib/pocompiler'>;
}
declare module 'gettext-parser/lib/poparser.js' {
  declare module.exports: $Exports<'gettext-parser/lib/poparser'>;
}
declare module 'gettext-parser/lib/shared.js' {
  declare module.exports: $Exports<'gettext-parser/lib/shared'>;
}
