// flow-typed signature: 43b316694328cbf959fa7d05dafe4890
// flow-typed version: <<STUB>>/kindlegen_v^1.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kindlegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kindlegen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kindlegen/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kindlegen/index' {
  declare module.exports: $Exports<'kindlegen'>;
}
declare module 'kindlegen/index.js' {
  declare module.exports: $Exports<'kindlegen'>;
}
declare module 'kindlegen/install.js' {
  declare module.exports: $Exports<'kindlegen/install'>;
}
