// flow-typed signature: c1d98796b12adb3be05104ccbb05cc7c
// flow-typed version: <<STUB>>/prompt-sync_v4.1.6/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prompt-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prompt-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prompt-sync/example' {
  declare module.exports: any;
}

declare module 'prompt-sync/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prompt-sync/example.js' {
  declare module.exports: $Exports<'prompt-sync/example'>;
}
declare module 'prompt-sync/index' {
  declare module.exports: $Exports<'prompt-sync'>;
}
declare module 'prompt-sync/index.js' {
  declare module.exports: $Exports<'prompt-sync'>;
}
declare module 'prompt-sync/test.js' {
  declare module.exports: $Exports<'prompt-sync/test'>;
}
