// flow-typed signature: a03b77a15eaa40af5b13b3c3421a37e3
// flow-typed version: <<STUB>>/promise-mysql_v^3.3.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-mysql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-mysql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-mysql/lib/connection' {
  declare module.exports: any;
}

declare module 'promise-mysql/lib/helper' {
  declare module.exports: any;
}

declare module 'promise-mysql/lib/pool' {
  declare module.exports: any;
}

declare module 'promise-mysql/lib/poolConnection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-mysql/index' {
  declare module.exports: $Exports<'promise-mysql'>;
}
declare module 'promise-mysql/index.js' {
  declare module.exports: $Exports<'promise-mysql'>;
}
declare module 'promise-mysql/lib/connection.js' {
  declare module.exports: $Exports<'promise-mysql/lib/connection'>;
}
declare module 'promise-mysql/lib/helper.js' {
  declare module.exports: $Exports<'promise-mysql/lib/helper'>;
}
declare module 'promise-mysql/lib/pool.js' {
  declare module.exports: $Exports<'promise-mysql/lib/pool'>;
}
declare module 'promise-mysql/lib/poolConnection.js' {
  declare module.exports: $Exports<'promise-mysql/lib/poolConnection'>;
}
