// flow-typed signature: d2686511a2d0d66a1a0cf1784e50cfd4
// flow-typed version: <<STUB>>/re-resizable_v4.11.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   're-resizable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 're-resizable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 're-resizable/lib/index.es5' {
  declare module.exports: any;
}

declare module 're-resizable/lib/index' {
  declare module.exports: any;
}

declare module 're-resizable/lib/re-resizable.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 're-resizable/lib/index.es5.js' {
  declare module.exports: $Exports<'re-resizable/lib/index.es5'>;
}
declare module 're-resizable/lib/index.js' {
  declare module.exports: $Exports<'re-resizable/lib/index'>;
}
declare module 're-resizable/lib/re-resizable.umd.js' {
  declare module.exports: $Exports<'re-resizable/lib/re-resizable.umd'>;
}
