// flow-typed signature: 03780f9494647ab080c0be1d561dc767
// flow-typed version: <<STUB>>/react-keyboard-event-handler_v^1.4.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-keyboard-event-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-keyboard-event-handler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-keyboard-event-handler/demo/dist/demo' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/demo/src/demo' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/lib/react-keyboard-event-handler' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/lib/react-keyboard-event-handler.min' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/src/index' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/src/KeyboardEventHandler' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/src/KeyboardEventHandler.spec' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/src/keyEvents' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/src/keyEvents.spec' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/webpack.config.demo' {
  declare module.exports: any;
}

declare module 'react-keyboard-event-handler/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-keyboard-event-handler/demo/dist/demo.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/demo/dist/demo'>;
}
declare module 'react-keyboard-event-handler/demo/src/demo.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/demo/src/demo'>;
}
declare module 'react-keyboard-event-handler/lib/react-keyboard-event-handler.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/lib/react-keyboard-event-handler'>;
}
declare module 'react-keyboard-event-handler/lib/react-keyboard-event-handler.min.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/lib/react-keyboard-event-handler.min'>;
}
declare module 'react-keyboard-event-handler/src/index.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/src/index'>;
}
declare module 'react-keyboard-event-handler/src/KeyboardEventHandler.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/src/KeyboardEventHandler'>;
}
declare module 'react-keyboard-event-handler/src/KeyboardEventHandler.spec.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/src/KeyboardEventHandler.spec'>;
}
declare module 'react-keyboard-event-handler/src/keyEvents.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/src/keyEvents'>;
}
declare module 'react-keyboard-event-handler/src/keyEvents.spec.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/src/keyEvents.spec'>;
}
declare module 'react-keyboard-event-handler/webpack.config.demo.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/webpack.config.demo'>;
}
declare module 'react-keyboard-event-handler/webpack.config.js' {
  declare module.exports: $Exports<'react-keyboard-event-handler/webpack.config'>;
}
