// flow-typed signature: 6edd75fe5cb7871904333aa022fad465
// flow-typed version: <<STUB>>/redux-starter-kit_v^0.2.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-starter-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-starter-kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-starter-kit/dist/redux-starter-kit.cjs' {
  declare module.exports: any;
}

declare module 'redux-starter-kit/dist/redux-starter-kit.esm' {
  declare module.exports: any;
}

declare module 'redux-starter-kit/dist/redux-starter-kit.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-starter-kit/dist/redux-starter-kit.cjs.js' {
  declare module.exports: $Exports<'redux-starter-kit/dist/redux-starter-kit.cjs'>;
}
declare module 'redux-starter-kit/dist/redux-starter-kit.esm.js' {
  declare module.exports: $Exports<'redux-starter-kit/dist/redux-starter-kit.esm'>;
}
declare module 'redux-starter-kit/dist/redux-starter-kit.umd.js' {
  declare module.exports: $Exports<'redux-starter-kit/dist/redux-starter-kit.umd'>;
}
