// flow-typed signature: 1429dc858bd5007f40e5ad3b2ac8a82e
// flow-typed version: <<STUB>>/right-pad_v^1.0.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'right-pad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'right-pad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'right-pad/examples/basic' {
  declare module.exports: any;
}

declare module 'right-pad/rightpad' {
  declare module.exports: any;
}

// Filename aliases
declare module 'right-pad/examples/basic.js' {
  declare module.exports: $Exports<'right-pad/examples/basic'>;
}
declare module 'right-pad/rightpad.js' {
  declare module.exports: $Exports<'right-pad/rightpad'>;
}
