// flow-typed signature: e3d1b75c4faef9cd0c69d158ee7ed6b7
// flow-typed version: <<STUB>>/roman-numerals_v^0.3.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roman-numerals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'roman-numerals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'roman-numerals/lib/toArabic' {
  declare module.exports: any;
}

declare module 'roman-numerals/lib/toRoman' {
  declare module.exports: any;
}

declare module 'roman-numerals/test/module' {
  declare module.exports: any;
}

declare module 'roman-numerals/test/toArabic' {
  declare module.exports: any;
}

declare module 'roman-numerals/test/toRoman' {
  declare module.exports: any;
}

// Filename aliases
declare module 'roman-numerals/index' {
  declare module.exports: $Exports<'roman-numerals'>;
}
declare module 'roman-numerals/index.js' {
  declare module.exports: $Exports<'roman-numerals'>;
}
declare module 'roman-numerals/lib/toArabic.js' {
  declare module.exports: $Exports<'roman-numerals/lib/toArabic'>;
}
declare module 'roman-numerals/lib/toRoman.js' {
  declare module.exports: $Exports<'roman-numerals/lib/toRoman'>;
}
declare module 'roman-numerals/test/module.js' {
  declare module.exports: $Exports<'roman-numerals/test/module'>;
}
declare module 'roman-numerals/test/toArabic.js' {
  declare module.exports: $Exports<'roman-numerals/test/toArabic'>;
}
declare module 'roman-numerals/test/toRoman.js' {
  declare module.exports: $Exports<'roman-numerals/test/toRoman'>;
}
