// flow-typed signature: f61c77e18a6708cec1b8cb9431aa1a46
// flow-typed version: <<STUB>>/smalltalk_v^3.2.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smalltalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smalltalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smalltalk/dist/smalltalk.min' {
  declare module.exports: any;
}

declare module 'smalltalk/dist/smalltalk.native.min' {
  declare module.exports: any;
}

declare module 'smalltalk/legacy/index' {
  declare module.exports: any;
}

declare module 'smalltalk/legacy/smalltalk' {
  declare module.exports: any;
}

declare module 'smalltalk/legacy/smalltalk.native' {
  declare module.exports: any;
}

declare module 'smalltalk/lib/smalltalk' {
  declare module.exports: any;
}

declare module 'smalltalk/lib/smalltalk.native' {
  declare module.exports: any;
}

declare module 'smalltalk/native/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smalltalk/dist/smalltalk.min.js' {
  declare module.exports: $Exports<'smalltalk/dist/smalltalk.min'>;
}
declare module 'smalltalk/dist/smalltalk.native.min.js' {
  declare module.exports: $Exports<'smalltalk/dist/smalltalk.native.min'>;
}
declare module 'smalltalk/legacy/index.js' {
  declare module.exports: $Exports<'smalltalk/legacy/index'>;
}
declare module 'smalltalk/legacy/smalltalk.js' {
  declare module.exports: $Exports<'smalltalk/legacy/smalltalk'>;
}
declare module 'smalltalk/legacy/smalltalk.native.js' {
  declare module.exports: $Exports<'smalltalk/legacy/smalltalk.native'>;
}
declare module 'smalltalk/lib/smalltalk.js' {
  declare module.exports: $Exports<'smalltalk/lib/smalltalk'>;
}
declare module 'smalltalk/lib/smalltalk.native.js' {
  declare module.exports: $Exports<'smalltalk/lib/smalltalk.native'>;
}
declare module 'smalltalk/native/index.js' {
  declare module.exports: $Exports<'smalltalk/native/index'>;
}
