// flow-typed signature: 909bab330a6c24165666cf6e7ca237f7
// flow-typed version: <<STUB>>/ttag_v^1.4.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ttag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ttag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ttag/dist/c3po' {
  declare module.exports: any;
}

declare module 'ttag/dist/c3po.min' {
  declare module.exports: any;
}

declare module 'ttag/dist/config' {
  declare module.exports: any;
}

declare module 'ttag/dist/index' {
  declare module.exports: any;
}

declare module 'ttag/dist/mock' {
  declare module.exports: any;
}

declare module 'ttag/dist/ttag' {
  declare module.exports: any;
}

declare module 'ttag/dist/ttag.min' {
  declare module.exports: any;
}

declare module 'ttag/dist/utils' {
  declare module.exports: any;
}

declare module 'ttag/dist/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ttag/dist/c3po.js' {
  declare module.exports: $Exports<'ttag/dist/c3po'>;
}
declare module 'ttag/dist/c3po.min.js' {
  declare module.exports: $Exports<'ttag/dist/c3po.min'>;
}
declare module 'ttag/dist/config.js' {
  declare module.exports: $Exports<'ttag/dist/config'>;
}
declare module 'ttag/dist/index.js' {
  declare module.exports: $Exports<'ttag/dist/index'>;
}
declare module 'ttag/dist/mock.js' {
  declare module.exports: $Exports<'ttag/dist/mock'>;
}
declare module 'ttag/dist/ttag.js' {
  declare module.exports: $Exports<'ttag/dist/ttag'>;
}
declare module 'ttag/dist/ttag.min.js' {
  declare module.exports: $Exports<'ttag/dist/ttag.min'>;
}
declare module 'ttag/dist/utils.js' {
  declare module.exports: $Exports<'ttag/dist/utils'>;
}
declare module 'ttag/dist/validation.js' {
  declare module.exports: $Exports<'ttag/dist/validation'>;
}
