// flow-typed signature: 442777dfb62d8b31685759f1f26389c2
// flow-typed version: <<STUB>>/unicharadata_v^9.0.0-alpha.6/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unicharadata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unicharadata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unicharadata/test' {
  declare module.exports: any;
}

declare module 'unicharadata/trial/unicharadata-embed' {
  declare module.exports: any;
}

declare module 'unicharadata/trial/unicharadata-load' {
  declare module.exports: any;
}

declare module 'unicharadata/unicharadata' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unicharadata/test.js' {
  declare module.exports: $Exports<'unicharadata/test'>;
}
declare module 'unicharadata/trial/unicharadata-embed.js' {
  declare module.exports: $Exports<'unicharadata/trial/unicharadata-embed'>;
}
declare module 'unicharadata/trial/unicharadata-load.js' {
  declare module.exports: $Exports<'unicharadata/trial/unicharadata-load'>;
}
declare module 'unicharadata/unicharadata.js' {
  declare module.exports: $Exports<'unicharadata/unicharadata'>;
}
