ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
= Kite

Derives `.pdf`, `.epub`, and `.mobi` from source `.adoc` Friends Library document repositories.

== Publish

The basic command structure is:

```sh
$ yarn kite publish <path>
```
But, the `publish` sub-command of `kite` is also considered the _default command_, so it can be left off:

```sh
$ yarn kite <path>
```
=== Publish `<path>` argument

Whatever `<path>` you pass it, `kite` will try to publish _all of the possible documents contained in that directory._
This allows you to publish a large group of documents, or narrow things down, as shown:

```sh
# publish all documents in all editions available in all languages
$ yarn kite

# publish all documents in all editions available in english
$ yarn kite en

# publish all george fox documents in all editions
$ yarn kite en/george-fox

# publish all versions of the journal
$ yarn kite en/george-fox/journal

# publish just the updated version of george fox's journal
$ yarn kite en/george-fox/journal/updated
```

=== Publish `--target`

There are currently 4 _target formats_ for kite to publish:

* `pdf-print`
* `pdf-web`
* `epub`
* `mobi`

The desired target can be passed with the `--target` flag:

[TIP]
If you don't supply a `--target` argument, the default is `pdf-print`.

```sh
$ yarn kite en/george-fox --target epub    # publish epub only
$ yarn kite en/george-fox --target mobi    # publish mobi only
$ yarn kite en/george-fox --target pdf-web # publish pdf-web only
```

You can also supply _more than one target_ by repeating the flag:

```sh
# publish epub AND pdf-print
$ yarn kite en/george-fox --target epub --target pdf-print
```

There are also a few _faux-targets_ made available for convenience sake:

* `pdf` -- shortcut for _both_ `pdf-print` and `pdf-web`
* `ebook` -- shortcut for _both_ `epub` and `mobi`
* `all` -- shortcut for _all possible targets_

```sh
$ yarn kite en/george-fox --target ebook # publish epub AND mobi
```

=== Publish `--glob`

By default, `kite` will join all of the `.adoc` files in the document directories
into a single asciidoc chunk before creating the derived formats.
If you would like to publish a smaller sub-set of the files, you can pass
a _glob pattern_ using the `--glob` flag.
The key concept is that only files will be selected which _match the glob pattern_,
and the `*` character means "match any number of any character".

The most common use case is to "publish" only a single file by targeting it's
conventional numeric prefix, like so:

```sh
# only select files that BEGIN with "04-"
$ yarn kite en/george-fox --glob 04-*
```

=== More Useful Flags:

Here's some brief documentation of some other useful flags:

```sh
# `--open` will open the created file/s in your default application
$ yarn kite en/george-fox --open

# `--no-frontmatter` will eliminate frontmatter (title page, toc, etc) when possible
$ yarn kite en/george-fox --no-frontmatter

# `--send` will email a copy of the created files (requires configuration, see below)
# this is especially useful for testing ebooks on phones and devices
$ yarn kite en/george-fox --send

# `--email` allows you to specify a custom email recipient (for use with `--send`)
$ yarn kite en/george-fox --send --email bob@gmail.com

# `--print-size` allows you to force a book print size (only with `pdf-print` target)
# possible sizes are `s`, `m`, (default), `l` (6x9), `xl`, and `xxl`
$ yarn kite en/george-fox --print-size l

# `--condense` adds css to slightly reduce number of pages for very long books
$ yarn kite en/daniel-wheeler/journal/original --condense --print-size l

# `--check` validates epubs using `epubcheck` (target `epub` only)
$ yarn kite en/george-fox --target epub --check
```


=== Flag/Argument Order:

When using the `kite` command, the `<path>` argument is required,
and _must come first_.
After that, the optional flags can come in _any order_:

```sh
# all three of these do the same thing
$ yarn kite en/george-fox --target epub --open --glob 04-*
$ yarn kite en/george-fox epub --open --target --glob 04-*
$ yarn kite en/george-fox --glob 04-* --target epub --open
```

[WARNING]
Note that while the _flags_ can come in any order, if a flag takes an _option_,
like the _epub_ in `--target *epub*`, it needs to be directly after its own flag.

== Configuration

`kite` uses a `.env` file for configuration. Main variables shown below, see `.env.example` for more granular detail:

```
DOCS_REPOS_ROOT=/path/to/root  # absolute filepath to source root dir containing all doc repos
PUBLISH_ROOT=/path/to/publish  # absolute filepath to destination (publish) root dir
GMAIL_PASS=lol-so-secret-password
GMAIL_USER=you@gmail.com
```

[TIP]
The `GMAIL_*` config options are required to use the `--send` option.
The `GMAIL_PASS` should be an _application-specific password_ you create for kite.
The `.env` file is gitignored, so it will never be made public.
