// flow-typed signature: f81aa7caa92c0a475ea3fcbbf868d118
// flow-typed version: <<STUB>>/epub-check_v^0.3.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'epub-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'epub-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'epub-check/index' {
  declare module.exports: $Exports<'epub-check'>;
}
declare module 'epub-check/index.js' {
  declare module.exports: $Exports<'epub-check'>;
}
