// flow-typed signature: e0906b519105b2a72f5418c1803fa2b4
// flow-typed version: <<STUB>>/gmail-send_v^1.2.14/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gmail-send'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gmail-send' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gmail-send/demo/demo' {
  declare module.exports: any;
}

declare module 'gmail-send/demo/multi-recipients' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gmail-send/demo/demo.js' {
  declare module.exports: $Exports<'gmail-send/demo/demo'>;
}
declare module 'gmail-send/demo/multi-recipients.js' {
  declare module.exports: $Exports<'gmail-send/demo/multi-recipients'>;
}
declare module 'gmail-send/index' {
  declare module.exports: $Exports<'gmail-send'>;
}
declare module 'gmail-send/index.js' {
  declare module.exports: $Exports<'gmail-send'>;
}
