version: 2
jobs:
  node:
    docker:
      - image: circleci/node:8.14.1
    working_directory: ~/fl-node
    steps:
      - checkout
      - restore_cache:
          key: v1-node-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-node-{{ checksum "yarn.lock" }}
      - run: yarn js:lint
      - run: yarn sass:lint
      - run: yarn js:test
      - run: yarn flow
      - run: yarn styleguide:build
      - run: yarn evans:build:en
      - run: yarn evans:build:es
      - run: yarn jones:build
  php:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    working_directory: ~/fl-php
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/phipps/composer.json" }}
      - run: cd packages/phipps && composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./packages/phipps/vendor
          key: v1-dependencies-{{ checksum "packages/phipps/composer.json" }}
      - run: cd packages/phipps && vendor/bin/phpunit
  deploy_api:
    docker:
      - image: circleci/node:8.14.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ce:27:a7:ac:8c:5d:4f:2b:0b:7c:f6:b8:8f:bb:e5:8b"
      - checkout
      - restore_cache:
          key: v1-node-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-node-{{ checksum "yarn.lock" }}
      - run: yarn api:deploy
workflows:
  version: 2
  test_node_and_php:
    jobs:
      - node
      - php
  deploy:
    jobs:
      - deploy_api:
          filters:
            branches:
              only:
                - master
