version: 2
jobs:
  node:
    docker:
      - image: circleci/node:8.14.1
    working_directory: ~/fl-node
    steps:
      - checkout
      - restore_cache:
          key: v1-node-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-node-{{ checksum "yarn.lock" }}
      - run: yarn js:lint
      - run: yarn sass:lint
      - run: yarn js:test
      - run: yarn flow
      - run: yarn styleguide:build
      - run: yarn evans:build:en
      - run: yarn evans:build:es
  php:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    working_directory: ~/fl-php
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/phipps/composer.json" }}
      - run: cd packages/phipps && composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./packages/phipps/vendor
          key: v1-dependencies-{{ checksum "packages/phipps/composer.json" }}
      - run: cd packages/phipps && vendor/bin/phpunit
workflows:
  version: 2
  test_node_and_php:
    jobs:
      - node
      - php
