// flow-typed signature: f560b6029c34c476a68f8e4774b8a2ed
// flow-typed version: <<STUB>>/@friends-library/friends_vfriends-library/friends#a19d386c90728e948671b00e2119b1417e2775f4/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@friends-library/friends'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@friends-library/friends' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@friends-library/friends/dist/__tests__/Document-tests' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/__tests__/Friend-tests' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/__tests__/map-tests' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/Audio' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/AudioPart' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/Chapter' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/Document' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/Edition' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/Format' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/Friend' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/index' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/map' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/query' {
  declare module.exports: any;
}

declare module '@friends-library/friends/dist/type' {
  declare module.exports: any;
}

declare module '@friends-library/friends/flow-typed/npm/glob_vx.x.x' {
  declare module.exports: any;
}

declare module '@friends-library/friends/flow-typed/npm/js-yaml_vx.x.x' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/__tests__/Document-tests' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/__tests__/Friend-tests' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/__tests__/map-tests' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/Audio' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/AudioPart' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/Chapter' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/Document' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/Edition' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/Format' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/Friend' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/index' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/map' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/query' {
  declare module.exports: any;
}

declare module '@friends-library/friends/src/type' {
  declare module.exports: any;
}

declare module '@friends-library/friends/yml/__tests__/spec.audio' {
  declare module.exports: any;
}

declare module '@friends-library/friends/yml/__tests__/spec.files' {
  declare module.exports: any;
}

declare module '@friends-library/friends/yml/test-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module '@friends-library/friends/dist/__tests__/Document-tests.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/__tests__/Document-tests'>;
}
declare module '@friends-library/friends/dist/__tests__/Friend-tests.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/__tests__/Friend-tests'>;
}
declare module '@friends-library/friends/dist/__tests__/map-tests.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/__tests__/map-tests'>;
}
declare module '@friends-library/friends/dist/Audio.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/Audio'>;
}
declare module '@friends-library/friends/dist/AudioPart.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/AudioPart'>;
}
declare module '@friends-library/friends/dist/Chapter.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/Chapter'>;
}
declare module '@friends-library/friends/dist/Document.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/Document'>;
}
declare module '@friends-library/friends/dist/Edition.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/Edition'>;
}
declare module '@friends-library/friends/dist/Format.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/Format'>;
}
declare module '@friends-library/friends/dist/Friend.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/Friend'>;
}
declare module '@friends-library/friends/dist/index.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/index'>;
}
declare module '@friends-library/friends/dist/map.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/map'>;
}
declare module '@friends-library/friends/dist/query.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/query'>;
}
declare module '@friends-library/friends/dist/type.js' {
  declare module.exports: $Exports<'@friends-library/friends/dist/type'>;
}
declare module '@friends-library/friends/flow-typed/npm/glob_vx.x.x.js' {
  declare module.exports: $Exports<'@friends-library/friends/flow-typed/npm/glob_vx.x.x'>;
}
declare module '@friends-library/friends/flow-typed/npm/js-yaml_vx.x.x.js' {
  declare module.exports: $Exports<'@friends-library/friends/flow-typed/npm/js-yaml_vx.x.x'>;
}
declare module '@friends-library/friends/src/__tests__/Document-tests.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/__tests__/Document-tests'>;
}
declare module '@friends-library/friends/src/__tests__/Friend-tests.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/__tests__/Friend-tests'>;
}
declare module '@friends-library/friends/src/__tests__/map-tests.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/__tests__/map-tests'>;
}
declare module '@friends-library/friends/src/Audio.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/Audio'>;
}
declare module '@friends-library/friends/src/AudioPart.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/AudioPart'>;
}
declare module '@friends-library/friends/src/Chapter.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/Chapter'>;
}
declare module '@friends-library/friends/src/Document.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/Document'>;
}
declare module '@friends-library/friends/src/Edition.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/Edition'>;
}
declare module '@friends-library/friends/src/Format.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/Format'>;
}
declare module '@friends-library/friends/src/Friend.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/Friend'>;
}
declare module '@friends-library/friends/src/index.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/index'>;
}
declare module '@friends-library/friends/src/map.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/map'>;
}
declare module '@friends-library/friends/src/query.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/query'>;
}
declare module '@friends-library/friends/src/type.js' {
  declare module.exports: $Exports<'@friends-library/friends/src/type'>;
}
declare module '@friends-library/friends/yml/__tests__/spec.audio.js' {
  declare module.exports: $Exports<'@friends-library/friends/yml/__tests__/spec.audio'>;
}
declare module '@friends-library/friends/yml/__tests__/spec.files.js' {
  declare module.exports: $Exports<'@friends-library/friends/yml/__tests__/spec.files'>;
}
declare module '@friends-library/friends/yml/test-helpers.js' {
  declare module.exports: $Exports<'@friends-library/friends/yml/test-helpers'>;
}
