[build]
  command = "yarn build:netlify"
  publish = "build"

[build.environment]
  YARN_VERSION = "1.21.1"
  NODE_VERSION = "12.13.1"
  DOCS_REPOS_ROOT = "/opt/build/repo/"
  DOCUMENT_META_GIST_FILENAME = "fl-doc-meta-v2.json"
  DOCUMENT_META_GIST_ID = "32117af9174d8c6bf3ba72956b6e60dc"
