[build]
  command = "export GATSBY_NETLIFY_CONTEXT=$CONTEXT && yarn build:netlify"
  publish = "public"
  functions = "functions"

[build.processing]
  skip_processing = false

[build.environment]
  DOCS_REPOS_ROOT = "/opt/build/repo/"
  YARN_VERSION = "1.21.1"
  NODE_VERSION = "12.13.1"
  AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"
  DOCUMENT_META_GIST_FILENAME = "fl-doc-meta-v2.json"
  DOCUMENT_META_GIST_ID = "32117af9174d8c6bf3ba72956b6e60dc"

[[redirects]]
  from = "/charles-marshall/short-journal"
  to = "/charles-marshall/journal-selection"
  status = 301
