name: ci-cd

on:
  push:
    branches-ignore:
      - master
      - actions
      - actions-*

env:
  FELL_GITHUB_TOKEN: ${{ secrets.FELL_GITHUB_TOKEN }}
  DOCUMENT_META_AUTH_TOKEN: ${{ secrets.DOCUMENT_META_AUTH_TOKEN }}
  DOCUMENT_META_GIST_ID: ${{ secrets.DOCUMENT_META_GIST_ID }}
  DOCUMENT_META_GIST_FILENAME: ${{ secrets.DOCUMENT_META_GIST_FILENAME }}
  CLOUD_STORAGE_BUCKET_URL: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
  DOCS_REPOS_ROOT: ${{ github.workspace }}

jobs:
  cancel:
    name: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1155909
          access_token: ${{ github.token }}

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: |
          yarn compile types
          yarn compile env
          yarn compile adoc-utils
          yarn compile adoc-lint
          yarn compile slack
          yarn compile cloud
          yarn compile lulu
          yarn compile doc-html
          yarn compile db
      - name: test
        run: yarn test -w=2

  ts-lint:
    name: ts-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: ts:lint
        run: yarn ts:lint

  jones-build:
    name: jones-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile jones
      - name: jones:build
        run: yarn jones:build

  evans-ts-check:
    name: evans-ts-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile evans
      - name: check-ts
        run: yarn evans:ts:check

  evans-build-en:
    name: evans-build-en
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile evans
      - name: fell-clone
        run: yarn fell:fresh-clone
      - name: evans-build-en
        run: yarn evans:build:en

  evans-build-es:
    name: evans-build-es
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile evans
      - name: fell-clone
        run: yarn fell:fresh-clone
      - name: evans-build-es
        run: yarn evans:build:es

  cover-build-and-check:
    name: cover-build-and-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile cover-web-app
      - name: cover:ts:check
        run: yarn cover:ts:check
      - name: cover:build
        run: yarn cover:build

  styleguide-build:
    name: styleguide-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: styleguide:build
        run: yarn styleguide:build

  storybook-build:
    name: storybook-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile ui
      - name: ui:build
        run: yarn ui:build:quiet
