name: deploy-editor

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  cancel:
    name: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1526116
          access_token: ${{ github.token }}

  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.meta.outputs.pull_request_number }}
      pull_request_title: ${{ steps.meta.outputs.pull_request_title }}
      latest_commit_sha: ${{ steps.meta.outputs.latest_commit_sha }}
      latest_commit_sha_short: ${{ steps.meta.outputs.latest_commit_sha_short }}
      should_deploy: ${{ steps.should_deploy.outputs.should_deploy_editor }}
      client_id: ${{ steps.prod.outputs.client_id || steps.preview.outputs.client_id }}
      context: ${{ steps.prod.outputs.context || steps.preview.outputs.context }}
    steps:
      - name: meta
        id: meta
        uses: friends-library/friends-library/actions/meta@actions
        with:
          github_token: ${{ github.token }}
      - name: should-deploy
        id: should_deploy
        uses: friends-library/friends-library/actions/should-deploy@actions
        with:
          site_id: editor
          github_token: ${{ github.token }}
      - name: set-prod-env
        id: prod
        if: steps.should_deploy.outputs.deploy_context == 'production'
        run: |
          echo "::set-output name=client_id=9b6f22aa47ed65ea8a6a"
          echo "::set-output name=context=production"
      - name: set-preview-env
        id: preview
        if: steps.should_deploy.outputs.deploy_context == 'preview'
        run: |
          echo "::set-output name=client_id::c57bcd3a00808c041852"
          echo "::set-output name=context::deploy-preview"

  english:
    name: english
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.should_deploy == 'true'
    outputs:
      deploy_url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile jones
      - name: jones-build-en
        env:
          REACT_APP_GITHUB_ORG: friends-library
          REACT_APP_OAUTH_CLIENT_ID: ${{ needs.setup.outputs.client_id }}
          REACT_APP_NETLIFY_CONTEXT: ${{ needs.setup.outputs.context }}
        run: yarn jones:build
      - name: deploy
        id: deploy
        if: success()
        uses: friends-library/friends-library/actions/deploy@actions
        with:
          netlify_api_token: ${{ secrets.NETLIFY_API_TOKEN }}
          site_id: ${{ secrets.EDITOR_NETLIFY_API_SITE_ID_EN }}
          build_dir: packages/jones/build
          github_token: ${{ github.token }}

  spanish:
    name: spanish
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.should_deploy == 'true'
    outputs:
      deploy_url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile jones
      - name: jones-build-en
        env:
          REACT_APP_GITHUB_ORG: biblioteca-de-los-amigos
          REACT_APP_OAUTH_CLIENT_ID: ${{ needs.setup.outputs.client_id }}
          REACT_APP_NETLIFY_CONTEXT: ${{ needs.setup.outputs.context }}
        run: yarn jones:build
      - name: deploy
        id: deploy
        if: success()
        uses: friends-library/friends-library/actions/deploy@actions
        with:
          netlify_api_token: ${{ secrets.NETLIFY_API_TOKEN }}
          site_id: ${{ secrets.EDITOR_NETLIFY_API_SITE_ID_ES }}
          build_dir: packages/jones/build
          github_token: ${{ github.token }}

  comment:
    name: comment
    runs-on: ubuntu-latest
    needs: [setup, english, spanish]
    if:
      needs.english.outputs.deploy_url && needs.spanish.outputs.deploy_url && github.ref
      != 'refs/heads/master'
    steps:
      - name: deploy-comment
        uses: peter-evans/commit-comment@v1
        with:
          sha: ${{ needs.setup.outputs.latest_commit_sha }}
          body: |
            Editor deploy previews for commit ${{ needs.setup.outputs.latest_commit_sha_short }}
            - English: [${{ needs.english.outputs.deploy_url }}](${{ needs.english.outputs.deploy_url }})
            - Spanish: [${{ needs.spanish.outputs.deploy_url }}](${{ needs.spanish.outputs.deploy_url }})
