name: deploy-storybook

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  cancel:
    name: cancel-previous-runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1525373
          access_token: ${{ github.token }}

  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.meta.outputs.pull_request_number }}
      pull_request_title: ${{ steps.meta.outputs.pull_request_title }}
      latest_commit_sha: ${{ steps.meta.outputs.latest_commit_sha }}
      latest_commit_sha_short: ${{ steps.meta.outputs.latest_commit_sha_short }}
      should_deploy: ${{ steps.should_deploy.outputs.should_deploy_storybook }}
    steps:
      - name: meta
        id: meta
        uses: friends-library/friends-library/actions/meta@actions
        with:
          github_token: ${{ github.token }}
      - name: should-deploy
        id: should_deploy
        uses: friends-library/friends-library/actions/should-deploy@actions
        with:
          site_id: storybook
          github_token: ${{ github.token }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.should_deploy == 'true'
    outputs:
      deploy_url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile ui
      - name: build
        run: yarn ui:build:quiet
      - name: deploy
        id: deploy
        if: success()
        uses: friends-library/friends-library/actions/deploy@actions
        with:
          netlify_api_token: ${{ secrets.NETLIFY_API_TOKEN }}
          site_id: ${{ secrets.STORYBOOK_NETLIFY_API_SITE_ID }}
          build_dir: packages/ui/storybook-static
          github_token: ${{ github.token }}

  comment:
    name: comment
    runs-on: ubuntu-latest
    needs: [setup, deploy]
    if: needs.deploy.outputs.deploy_url && github.ref != 'refs/heads/master'
    steps:
      - name: deploy-comment
        uses: peter-evans/commit-comment@v1
        with:
          sha: ${{ needs.setup.outputs.latest_commit_sha }}
          body: |
            Storybook deploy preview for commit ${{ needs.setup.outputs.latest_commit_sha_short }}
            - [${{ needs.deploy.outputs.deploy_url }}](${{ needs.deploy.outputs.deploy_url }})
