name: deploy-site

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

env:
  FELL_GITHUB_TOKEN: ${{ secrets.FELL_GITHUB_TOKEN }}
  DOCUMENT_META_AUTH_TOKEN: ${{ secrets.DOCUMENT_META_AUTH_TOKEN }}
  DOCUMENT_META_GIST_ID: ${{ secrets.DOCUMENT_META_GIST_ID }}
  DOCUMENT_META_GIST_FILENAME: ${{ secrets.DOCUMENT_META_GIST_FILENAME }}
  CLOUD_STORAGE_BUCKET_URL: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
  GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  GATSBY_ALGOLIA_SEARCH_ONLY_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_ONLY_KEY }}
  GATSBY_TEST_STRIPE_PUBLISHABLE_KEY: ${{ secrets.GATSBY_TEST_STRIPE_PUBLISHABLE_KEY }}
  GATSBY_PROD_STRIPE_PUBLISHABLE_KEY: ${{ secrets.GATSBY_PROD_STRIPE_PUBLISHABLE_KEY }}
  DOCS_REPOS_ROOT: ${{ github.workspace }}
  DEPLOYING: true

jobs:
  cancel:
    name: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1212221
          access_token: ${{ github.token }}

  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.meta.outputs.pull_request_number }}
      pull_request_title: ${{ steps.meta.outputs.pull_request_title }}
      latest_commit_sha: ${{ steps.meta.outputs.latest_commit_sha }}
      latest_commit_sha_short: ${{ steps.meta.outputs.latest_commit_sha_short }}
      should_deploy_site: ${{ steps.should_deploy.outputs.should_deploy_site }}
      deploy_context: ${{ steps.should_deploy.outputs.deploy_context }}
    steps:
      - name: meta
        id: meta
        uses: friends-library/friends-library/actions/meta@actions
        with:
          github_token: ${{ github.token }}
      - name: should-deploy
        id: should_deploy
        uses: friends-library/friends-library/actions/should-deploy@actions
        with:
          site_id: site
          github_token: ${{ github.token }}

  english:
    name: english
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.should_deploy_site == 'true'
    outputs:
      deploy_url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile evans
      - name: fell-clone
        run: yarn fell:fresh-clone
      - name: evans-build-en
        env:
          GATSBY_NETLIFY_CONTEXT: ${{ needs.setup.outputs.deploy_context }}
        run: yarn evans:build:en
      - name: deploy
        id: deploy
        if: success()
        uses: friends-library/friends-library/actions/deploy@actions
        with:
          netlify_api_token: ${{ secrets.NETLIFY_API_TOKEN }}
          site_id: ${{ secrets.DEPLOY_SITE_ID_EN }}
          build_dir: packages/evans/public
          functions_dir: packages/functions/dist
          github_token: ${{ github.token }}

  spanish:
    name: spanish
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.should_deploy_site == 'true'
    outputs:
      deploy_url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: compile
        run: yarn compile evans
      - name: fell-clone
        run: yarn fell:fresh-clone
      - name: evans-build-es
        env:
          GATSBY_NETLIFY_CONTEXT: ${{ needs.setup.outputs.deploy_context }}
        run: yarn evans:build:es
      - name: deploy
        id: deploy
        if: success()
        uses: friends-library/friends-library/actions/deploy@actions
        with:
          netlify_api_token: ${{ secrets.NETLIFY_API_TOKEN }}
          site_id: ${{ secrets.DEPLOY_SITE_ID_ES }}
          build_dir: packages/evans/public
          functions_dir: packages/functions/dist
          github_token: ${{ github.token }}

  comment:
    name: comment
    runs-on: ubuntu-latest
    needs: [setup, english, spanish]
    if:
      needs.english.outputs.deploy_url && needs.spanish.outputs.deploy_url && github.ref
      != 'refs/heads/master'
    steps:
      - name: deploy-comment
        uses: peter-evans/commit-comment@v1
        with:
          sha: ${{ needs.setup.outputs.latest_commit_sha }}
          body: |
            Deploy previews for commit ${{ needs.setup.outputs.latest_commit_sha_short }}
            - English: [${{ needs.english.outputs.deploy_url }}](${{ needs.english.outputs.deploy_url }})
            - Spanish: [${{ needs.spanish.outputs.deploy_url }}](${{ needs.spanish.outputs.deploy_url }})
