name: print-jobs

on: [push]

env:
  DOCUMENT_META_AUTH_TOKEN: ${{ secrets.DOCUMENT_META_AUTH_TOKEN }}
  DOCUMENT_META_GIST_ID: ${{ secrets.DOCUMENT_META_GIST_ID }}
  DOCUMENT_META_GIST_FILENAME: ${{ secrets.DOCUMENT_META_GIST_FILENAME }}
  FRIENDS_YML_PATH: ${{ github.workspace }}/packages/friends/yml
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}

jobs:
  print_jobs:
    name: do-a-thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: friends-library/friends-library/actions/print-jobs@actions-print-jobs
        with:
          lulu_client_key: ${{ secrets.TEST_LULU_CLIENT_KEY }}
          lulu_client_secret: ${{ secrets.TEST_LULU_CLIENT_SECRET }}
          lulu_is_sandbox: true
          fauna_server_secret: ${{ secrets.TEST_FAUNA_SERVER_SECRET }}
          cloud_storage_bucket_url: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
