name: print-jobs

# handled by new `cron` package in `friends-library-dev` org
# this file just left for historical purposes
# the `on` value below should guarantee this file never runs
on:
  push:
    branches:
      - never-run-ca0bdbb3-1ee5-4027-b6df-9f5a803423d6

# below was original `on`
# on:
#   schedule:
#     - cron: 0 * * * *

env:
  FRIENDS_YML_PATH: ${{ github.workspace }}/packages/friends/yml
  DOCUMENT_META_AUTH_TOKEN: ${{ secrets.DOCUMENT_META_AUTH_TOKEN }}
  DOCUMENT_META_GIST_ID: ${{ secrets.DOCUMENT_META_GIST_ID }}
  DOCUMENT_META_GIST_FILENAME: ${{ secrets.DOCUMENT_META_GIST_FILENAME }}
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}

jobs:
  print_jobs:
    name: process-print-jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: friends-library/friends-library/actions/print-jobs@actions
        with:
          lulu_client_key: ${{ secrets.PROD_LULU_CLIENT_KEY }}
          lulu_client_secret: ${{ secrets.PROD_LULU_CLIENT_SECRET }}
          lulu_is_sandbox: false
          fauna_server_secret: ${{ secrets.PROD_FAUNA_SERVER_SECRET }}
          cloud_storage_bucket_url: ${{ secrets.CLOUD_STORAGE_BUCKET_URL }}
