name: slack-clean

# handled by new `cron` package in `friends-library-dev` org
# this file just left for historical purposes
# the `on` value below should guarantee this file never runs
on:
  push:
    branches:
      - never-run-ca0bdbb3-1ee5-4027-b6df-9f5a803423d6

# below was original `on`
# on:
#   schedule:
#     - cron: 0 0,12 * * *

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: set-env
        run: |
          echo ::set-env name=FIVE_DAYS_AGO::$(date -d '-5 days' '+%Y%m%d')
          echo ::set-env name=THREE_DAYS_AGO::$(date -d '-3 days' '+%Y%m%d')
          echo ::set-env name=TWO_DAYS_AGO::$(date -d '-2 days' '+%Y%m%d')
          echo ::set-env name=ONE_DAY_AGO::$(date -d '-1 days' '+%Y%m%d')
      - name: clean downloads channel
        uses: matken11235/slack-cleaner@v1
        with:
          group: downloads
          before: ${{ env.FIVE_DAYS_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
      - name: clean errors channel
        uses: matken11235/slack-cleaner@v1
        with:
          group: errors
          before: ${{ env.FIVE_DAYS_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
      - name: clean msf-errors channel
        uses: matken11235/slack-cleaner@v1
        with:
          group: msf-errors
          before: ${{ env.THREE_DAYS_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
      - name: clean info channel
        uses: matken11235/slack-cleaner@v1
        with:
          group: info
          before: ${{ env.TWO_DAYS_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
      - name: clean debug channel
        uses: matken11235/slack-cleaner@v1
        with:
          group: debug
          before: ${{ env.THREE_DAYS_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
      - name: clean dev channel
        uses: matken11235/slack-cleaner@v1
        with:
          channel: dev
          before: ${{ env.FIVE_DAYS_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
      - name: clean staging channel
        uses: matken11235/slack-cleaner@v1
        with:
          group: staging
          before: ${{ env.ONE_DAY_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
      - name: clean audio channel
        uses: matken11235/slack-cleaner@v1
        with:
          group: audio-downloads
          before: ${{ env.ONE_DAY_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
      - name: clean spendable channel
        uses: matken11235/slack-cleaner@v1
        with:
          group: spendable
          before: ${{ env.FIVE_DAYS_AGO }}
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_CLEANER_TOKEN }}
