name: slack-clean

on:
  schedule:
    - cron: 0 0,12 * * *

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: matken11235/slack-cleaner@v1
        with:
          group: downloads
          before: '`date -d "-5 days" "+%Y%m%d"`'
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_LEGACY_TOKEN }}
      - uses: matken11235/slack-cleaner@v1
        with:
          group: errors
          before: '`date -d "-3 days" "+%Y%m%d"`'
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_LEGACY_TOKEN }}
      - uses: matken11235/slack-cleaner@v1
        with:
          group: fnlogs
          before: '`date -d "+1 days" "+%Y%m%d"`'
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_LEGACY_TOKEN }}
      - uses: matken11235/slack-cleaner@v1
        with:
          group: test-bot
          before: '`date -d "-1 days" "+%Y%m%d"`'
          rate: '1'
          message: true
          bot: true
          perform: true
          token: ${{ secrets.SLACK_LEGACY_TOKEN }}
