name: order-tracking-emails

# handled by new `cron` package in `friends-library-dev` org
# this file just left for historical purposes
# the `on` value below should guarantee this file never runs
on:
  push:
    branches:
      - never-run-ca0bdbb3-1ee5-4027-b6df-9f5a803423d6

# below was original `on`
# on:
#   schedule:
#     # every six hours
#     - cron: 0 0,6,12,18 * * *

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      ENDPOINT: ${{ secrets.TRACKING_EMAILS_CRON_URL }}
    steps:
      # send HTTP request, exit 0 only if status code = 200
      - name: Send HTTP request
        run: curl -s -o /dev/null -w "%{http_code}" -X POST $ENDPOINT -d "" | grep -q 200
